"""
加载 .env；仅密钥/交易对/风控/下单规模等少数项走环境变量，其余默认见类 D（原 quant.defaults）。
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv

    load_dotenv(_ROOT / ".env", override=True)
except ImportError:
    pass


def _eb(k: str, default: bool) -> bool:
    raw = os.environ.get(k)
    if raw is None or not raw.strip():
        return default
    v = raw.strip().lower()
    if v in ("1", "true", "yes"):
        return True
    if v in ("0", "false", "no"):
        return False
    return default


def _ei(k: str, default: int) -> int:
    raw = os.environ.get(k, "").strip()
    if not raw:
        return default
    return int(raw)


def _es(k: str, default: str) -> str:
    return os.environ.get(k, default).strip()


def _ef(k: str, default: float) -> float:
    raw = os.environ.get(k, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


class D:
    """Former quant.defaults (inlined)."""

    # --- REST 行情（与 quant.exchange.okx_public 一致）---
    REST_POLL_INTERVAL_SEC = 0.5
    REST_CANDLES_BAR = "1m"
    REST_CANDLES_LIMIT = 120
    REST_HTTP_TIMEOUT_SEC = 90.0
    REST_HTTP_CONNECT_TIMEOUT_SEC = 45.0
    # 公共 REST 附带拉取盘口深度（OKX GET /api/v5/market/books）
    REST_ORDER_BOOK_SZ = 5
    REST_SNAPSHOT_SLOW_INTERVAL_SEC = 4.0

    # --- 日志 / 审计 / 熔断 / 对账 ---
    LOG_TO_FILE = True
    LOG_JSONL_SNAPSHOTS = True
    # 按日分类的离线超详细 JSONL（见 quant/detailed_daily_log.py）
    DETAILED_DAILY_LOG = True
    DETAILED_LOG_PURGE_LEGACY = True
    # 0 = 每个 tick 都写 market.jsonl；设为 0.5~2 可降磁盘写入量
    DETAILED_LOG_TICK_MIN_SEC = 0.0
    AUDIT_ENABLED = True
    METRICS_INTERVAL_SEC = 50.0
    CIRCUIT_MAX_FAILS = 5
    CIRCUIT_COOLDOWN_SEC = 120.0
    RECONCILE_INTERVAL_SEC = 300.0
    STRAT_DECISION_LOG = True
    STRAT_DECISION_LOG_MIN_SEC = 8.0
    ACCOUNT_SNAPSHOT_ON_START = True
    ACCOUNT_SNAPSHOT_INTERVAL_SEC = 0.0
    STRAT_BALANCE_POLL_SEC = 20.0
    STRAT_INVENTORY_LOG_SEC = 60.0
    # 僵尸挂单撤销：60s 内未成交的限价单直接撤销
    # 实测平均网络延迟 7.2s，20s 阈值导致实际填单窗口只有 12.8s，大量信号超时放弃
    # 60s 给回撤信号足够时间等待价格反弹，同时防止僵尸挂单积累
    STRAT_STALE_ORDER_CANCEL_SEC = 60.0
    STRAT_STALE_ORDER_POLL_SEC = 30.0

    # --- 风控缓冲（发单前余额校验）---
    RISK_CHECK_BALANCE = True
    RISK_BALANCE_BUFFER_PCT = 0.002
    RISK_MAX_CORR_NOTIONAL_USDT = ""
    # 启用 CorrelationGuard 时：额外高频拉 orders-pending 覆盖乐观敞口（秒）；0=关闭
    RISK_CORR_RESYNC_INTERVAL_SEC = 18.0
    # 为真时：无 USDT 可用余额快照则拦截开仓保证金预检（更保守；需余额接口稳定）
    RISK_MARGIN_PRECHECK_STRICT = False
    RISK_DAILY_MAX_LOSS_PCT = 0.02
    RISK_HALF_KELLY_ENABLE = True
    RISK_HALF_KELLY_WINDOW = 100
    RISK_HALF_KELLY_MIN_SAMPLES = 50
    RISK_HALF_KELLY_CONSERVATIVE_CONTRACTS = 0.01
    FUNDING_BILLS_ENABLE = True
    FUNDING_BILLS_FETCH_INTERVAL_SEC = 300.0

    STRAT_ORDER_BASE_DECIMALS = 5
    STRAT_ORDER_SZ = "1"
    STRAT_PRICE_DECIMALS = 2

    LEV5_ENABLED = True
    LEV5_LEVERAGE = 5.0
    LEV5_TD_MODE = "isolated"
    LEV5_POS_MODE = "long_short"
    LEV5_ORDER_SIZE_CONTRACT = "1"
    # EMA 参数：小步快走需要更快的趋势感知
    # α=0.12 约等于 8 tick 半衰期（WS 模式下约 1s），对短线微趋势响应更及时
    # α=0.04 约等于 25 tick 半衰期，作为稳定基准，保证趋势信号不过于噪声
    LEV5_EMA_FAST_ALPHA = 0.12
    LEV5_EMA_SLOW_ALPHA = 0.04
    # 回撤阈值：从 0.32σ 降至 0.20σ，捕捉更浅的回撤入场机会
    # 参考 Bollinger 理论：1/4σ 级别回撤在趋势中具有正期望收益，配合预测门过滤噪声
    LEV5_PULLBACK_Z = 0.20
    LEV5_PULLBACK_Z_DIRECTION_TOLERANCE = 0.5
    LEV5_TREND_EPS = 0.000060  # 提高：trend_min_str=eps×5=0.00030，过滤 ts<0.0003 弱趋势假信号
    # 止损/止盈：小步快走核心参数
    # SL=0.5%（价格），5倍杠杆 → 2.5% 账户损失/笔；TP=0.8% → 4% 账户收益/笔
    # 费率约 7bps（maker 进 + IOC 出），每笔手续费 ≈ 0.07% 价格，TP 覆盖率 91%
    # Kelly 最优分数：胜率 55%、RR 1.6:1 → 每笔正期望 = 0.55×0.8% - 0.45×0.5% - 0.07% ≈ 0.145%
    LEV5_STOP_LOSS_PCT = 0.005
    LEV5_TAKE_PROFIT_PCT = 0.008
    # 最大持仓时间：300s（5 分钟）；超过此时间的持仓属于中线逻辑，与小步快走不符
    LEV5_MAX_HOLD_SEC = 300.0
    # 动态止损/止盈乘数：基于实时波动率缩放，低波动时收紧、高波动时放宽
    # 降低乘数使区间更紧，配合小步快走加快盈利锁定
    LEV5_SL_VOL_MULT = 3.0
    LEV5_TP_VOL_MULT = 5.0
    # 地板/天花板：确保止损/止盈在合理区间
    # SL_FLOOR=0.4%：低于此市场噪声会直接触发；SL_CEIL=1.0%：超过此则持仓过大
    LEV5_SL_PCT_FLOOR = 0.004
    LEV5_SL_PCT_CEIL = 0.010
    LEV5_TP_PCT_FLOOR = 0.006
    LEV5_TP_PCT_CEIL = 0.018
    # 风险回报比下限 1.55：确保即使胜率只有 40% 也能盈利
    LEV5_TP_RR_MIN = 1.55
    LEV5_Z_NEED_MAX = 1.00
    LEV5_CONTINUATION_ENABLE = True
    # Continuation 通道：趋势延续入场，z_min 从 0.28 降至 0.16，捕捉更早的动量信号
    LEV5_CONTINUATION_Z_MIN = 0.16
    LEV5_CONTINUATION_Z_MAX = 0.90
    LEV5_CONTINUATION_IMB_LONG = 0.0
    LEV5_CONTINUATION_IMB_SHORT = 0.0
    # Continuation 仓位因子提升：高质量趋势延续信号值得更大仓位
    LEV5_CONTINUATION_SIZE_FACTOR = 0.80
    LEV5_CONTINUATION_MIN_ABS_Z = 0.16
    # 趋势强度要求降低：小步快走不要求强趋势，弱趋势也有盈利空间
    LEV5_CONTINUATION_MIN_TREND_STRENGTH = 0.000020
    LEV5_BREAKOUT_ADX_MIN = 35.0
    LEV5_TREND_ORDER_TYPE_OVERRIDE = "limit"
    LEV5_TREND_ORDER_TYPE_ADX_MIN = 45.0
    # 震荡市额外 Z 门槛：震荡期回撤信号质量差，额外 0.10 过滤噪声
    LEV5_CHOP_PULLBACK_EXTRA_Z_NEED = 0.10
    LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS = 0.02
    LEV5_MIN_EDGE_EFFECTIVE_CEIL_BPS = 2.0
    LEV5_REST_FAIL_STREAK_WARN = 6
    LEV5_REST_FAIL_EXTRA_Z_NEED = 0.06
    LEV5_AUTOTUNE_Z_ADD_FLOOR = -0.12
    LEV5_AUTOTUNE_Z_ADD_FLOOR_FORCED = -0.20
    LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR = -0.88
    LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR_FORCED = -1.12
    # 僵尸持仓：持仓 3 分钟内若 PnL 绝对值 < 0.06% 视为卡单，直接平仓
    # 小步快走要求持仓快速流动，卡单占用保证金且阻断新机会
    LEV5_STALE_HOLD_SEC = 180.0
    LEV5_STALE_PNL_ABS_PCT = 0.0006
    # 快速亏损止损：持仓 60s 后亏损已达 SL 的 65% → 立即平仓（"快刀斩乱麻"）
    # 原理：若方向判断错误，价格通常在前 60s 内已明显偏离，早出比死扛更优
    LEV5_QUICK_LOSS_EXIT_HOLD_SEC = 60.0
    LEV5_QUICK_LOSS_EXIT_SL_FRAC = 0.65
    # 强制平仓上限：6 分钟。所有持仓在 6 分钟内必须退出，防止中线亏损滚雪球
    LEV5_FORCE_CUT_HOLD_SEC = 360.0
    LEV5_LEGACY_RELAX_ENABLE = True
    LEV5_REGIME_CHOP_STRENGTH_MAX = 0.000048
    LEV5_BLOCK_ENTRIES_IN_CHOP = False
    LEV5_MIN_TREND_STRENGTH_ENTRY = 0.0
    LEV5_PREDICTION_GATE_ENABLE = True
    # 预测分门槛：从 0.52 降至 0.48，让更多信号通过预测门
    # 配合更紧的 SL（0.5%），错误信号代价更小，可承受更低的预测分门槛
    LEV5_PREDICTION_MIN_SCORE = 0.48
    # 震荡市预测分门槛：略高于普通门槛，震荡期信号质量差需要更高确信度
    LEV5_PREDICTION_MIN_SCORE_CHOP = 0.60
    LEV5_BOOK_IMB_EWM_ALPHA = 0.12
    LEV5_PRED_WEIGHT_TREND = 0.18
    LEV5_PRED_WEIGHT_PULLBACK = 0.22
    LEV5_PRED_WEIGHT_IMB = 0.18
    LEV5_PRED_WEIGHT_EDGE = 0.14
    LEV5_PRED_WEIGHT_CANDLE = 0.12
    LEV5_PRED_WEIGHT_SPREAD = 0.08
    LEV5_PRED_WEIGHT_REL_VOL = 0.08
    LEV5_PRED_EDGE_SURPLUS_SCALE_BPS = 12.0
    LEV5_PRED_SPREAD_REF_PCT = 0.00075
    LEV5_PRED_REL_VOL_LO = 0.00045
    LEV5_PRED_REL_VOL_HI = 0.0045
    LEV5_POST_ONLY_IMPROVE_BPS = 0.28
    # 余额低位阈值：账户 <25 USDT 时触发 stuck_quote 逻辑（60 USDT 账户需降低阈值）
    LEV5_QUOTE_LOW_USDT = 25.0
    # 资金不足持仓平出：持仓 120s 后余额不足且 PnL 很小 → 平仓释放保证金
    LEV5_STUCK_QUOTE_LITE_SEC = 120.0
    LEV5_STUCK_QUOTE_PNL_ABS = 0.0010
    LEV5_FUNDING_BLEED_HOLD_SEC = 900.0
    LEV5_FUNDING_BLEED_FR_ABS = 6.0e-06
    LEV5_FUNDING_BLEED_MAX_PNL_FRAC_TP = 0.35
    LEV5_ACCOUNT_POS_POLL_SEC = 22.0
    LEV5_GHOST_RECONCILE_MIN_SEC = 45.0
    LEV5_CH_AUTOTUNE_ENABLE = True
    LEV5_CH_AUTOTUNE_STEP = 0.018
    LEV5_CH_W_ADJ_MIN = 0.80
    LEV5_CH_W_ADJ_MAX = 1.15
    LEV5_CH_PERF_EMA_ALPHA = 0.22
    # 通道权重：小步快走提升 continuation 和 micro 通道权重
    # Pullback 仍最高优先，但 continuation（趋势延续）是高频入场的关键通道
    # Micro（盘口失衡）权重提高：微结构信号是高频策略的核心优势
    LEV5_CH_W_PULLBACK_LONG = 1.0
    LEV5_CH_W_CONTINUATION_LONG = 0.82
    LEV5_CH_W_MICRO_LONG = 0.80
    LEV5_CH_W_VOL_LONG = 0.68
    LEV5_CH_W_FUNDING_LONG = 0.36
    LEV5_CH_W_PULLBACK_SHORT = 1.0
    LEV5_CH_W_CONTINUATION_SHORT = 0.82
    LEV5_CH_W_MICRO_SHORT = 0.80
    LEV5_CH_W_VOL_SHORT = 0.68
    LEV5_CH_W_FUNDING_SHORT = 0.40
    # Merit 门槛降低：从 0.58/0.62 降至 0.50/0.52，让更多通道组合通过
    # 降低此门槛的风险由紧缩的 SL 和 prediction gate 兜底
    LEV5_MERIT_MIN_LONG = 0.50
    LEV5_MERIT_MIN_SHORT = 0.52
    LEV5_CH_FUNDING_STACK_FRAC = 0.55
    LEV5_CH_MICRO_ENABLE = True
    # Micro 通道盘口失衡灵敏度提高：0.08 代替 0.10，更早捕捉买卖压力失衡
    # 订单簿失衡是高频市场的先行指标，在 ETH 永续中效果显著
    LEV5_MICRO_IMB_LONG = 0.08
    LEV5_MICRO_IMB_SHORT = -0.08
    LEV5_MICRO_Z_MAX_ABS = 0.80
    LEV5_CH_VOL_BREAK_ENABLE = True
    LEV5_VOL_BREAK_REL_FRAC = 0.85
    LEV5_VOL_BREAK_Z_PAD = 0.30
    LEV5_CH_FUNDING_ALIGN_ENABLE = True
    LEV5_FUNDING_ALIGN_ABS = 4.0e-06
    # Micro/Vol 通道仓位因子提高：高质量微结构信号值得更大仓位（但不超过主仓位）
    LEV5_CH_SIZE_MICRO = 0.85
    LEV5_CH_SIZE_VOL = 0.70
    LEV5_CH_SIZE_FUNDING = 0.55
    LEV5_GUARD_POLL_SEC = 5.0
    LEV5_DAILY_DD_LIMIT_PCT = 0.06
    # 最大连续亏损次数：从 3 调整到 5
    # 小步快走 SL 收紧，连续亏损更可能发生，5 次后暂停更合适
    # 5 × 0.5% × 5倍杠杆 = 12.5% 账户亏损前暂停，有机会人工检查市场
    LEV5_MAX_CONSEC_LOSS = 5
    LEV5_TRADING_HOURS_UTC = ""
    # 波动率目标：ETH 1min bar 典型相对波动率约 0.0015，目标稍低以避免过度缩仓
    LEV5_VOL_TARGET = 0.0014
    # 波动率软上限：超过 0.0030 时开始缩减仓位（高波动意味着更大滑点和 SL 触发风险）
    LEV5_VOL_SOFT_CEIL = 0.0030
    LEV5_MIN_SIZE_FACTOR = 0.50
    # 非活跃时段 Z 加成：降低门槛吸引更多信号
    LEV5_OFFHOUR_Z_BONUS = 0.08
    LEV5_HIGHVOL_Z_BONUS = 0.20
    LEV5_HALT_COOLDOWN_SEC = 1800.0
    # 金字塔加仓：小步快走禁用，60 USDT 账户保证金有限，加仓会占用新机会的资金
    LEV5_PYRAMID_ENABLE = False
    LEV5_PYRAMID_STEP_PCT = 0.010
    LEV5_PYRAMID_MAX_LAYERS = 0
    LEV5_SCALEOUT_ENABLE = False
    LEV5_SCALEOUT_STEP_PCT = 0.006
    # 移动止盈：到达盈亏平衡点（0.3%）后启动追踪，最大回撤 0.2% 后退出
    # 原理：锁住已有利润，避免因等待更高 TP 而吐回盈利
    LEV5_TRAIL_ENABLE = True
    LEV5_BREAK_EVEN_TRIGGER_PCT = 0.003
    LEV5_TRAIL_GIVEBACK_PCT = 0.002
    # 风险预算：1.5% 账户/笔（含杠杆效应，对应 0.3% 价格 SL）
    LEV5_RISK_BUDGET_PCT = 0.015
    LEV5_CT_VAL_BASE = 0.01
    # OKX ETH-USDT-SWAP：minSz=1 contract=0.01ETH；最大 3 张避免过度集中
    LEV5_MIN_CONTRACTS = 1.0
    LEV5_MAX_CONTRACTS = 3
    LEV5_EXEC_SPREAD_FOR_POST_BPS = 0.8
    LEV5_EXEC_HIGH_VOL_FOR_IOC = 0.0028
    LEV5_FUNDING_PENALTY_RATE = 0.0008
    # 往返手续费估计：maker 进（2bps）+ IOC 出（5bps）= 7bps，用实际值替换低估的 10
    LEV5_ROUNDTRIP_FEE_BPS = 7.0
    # 最低净边际：允许略低的 net_edge，配合更严格的预测门过滤，不额外过滤信号
    LEV5_MIN_NET_EDGE_BPS = 0.02
    # Runner：对 lev5 开仓意图再筛一层 OrderIntent.features_json["net_edge_bps"]；0=关闭（默认）
    LEV5_RUNNER_FEE_GATE_MIN_NET_EDGE_BPS = 0.0
    LEV5_FUNDING_WINDOW_MIN = 10
    LEV5_FUNDING_WINDOW_Z_BONUS = 0.20
    LEV5_MICRO_POLL_SEC = 2.5
    LEV5_PREMIUM_ALERT_PCT = 0.0035
    LEV5_OI_DELTA_ALERT_PCT = 0.055
    LEV5_SELFCHECK_LOG_SEC = 60.0
    LEV5_BOOK_IMBALANCE_ALERT = 0.58
    # 信号确认窗口：0.224s（保持）；REST 1s 轮询下确认窗口实际作用为"两个连续同向 tick"
    # 降低确认门槛但保留双 tick 机制，避免单 tick 噪声入场
    LEV5_CONFIRM_WINDOW_SEC = 0.224
    LEV5_CONFIRM_Z_RELAX = 0.65
    LEV5_CONFIRM_ADAPT_ENABLE = True
    LEV5_CONFIRM_FAIL_HIGH = 0.60
    LEV5_CONFIRM_FAIL_LOW = 0.40
    # 确认窗口范围：最短 0.3s（快速确认），最长 3s（超过则信号已过时）
    LEV5_CONFIRM_WINDOW_MIN_SEC = 0.30
    LEV5_CONFIRM_WINDOW_MAX_SEC = 3.0
    LEV5_IMB_AGAINST_Z_BONUS = 0.10
    LEV5_IMB_WITH_Z_BONUS = 0.06
    LEV5_STALE_MICRO_SEC = 8.0
    LEV5_STALE_SIZE_FACTOR = 0.60
    LEV5_TUNE_INTERVAL_SEC = 120.0
    LEV5_TUNE_Z_STEP = 0.03
    LEV5_TUNE_EDGE_STEP_BPS = 0.30
    LEV5_EDGE_MODEL_ENABLED = True
    LEV5_EDGE_Z_K_BPS = 5.5
    LEV5_EDGE_IMB_K_BPS = 3.0
    LEV5_EDGE_PREMIUM_K_BPS = 2.0
    LEV5_EDGE_SAFETY_BPS = 0.42
    LEV5_TUNE_MAX_STEP_SCALE = 1.0
    LEV5_TUNE_FREEZE_VOL = 0.0038
    LEV5_TUNE_FREEZE_PREMIUM = 0.0022
    LEV5_MODEL_DIAG_INTERVAL_SEC = 300.0
    LEV5_MODEL_DIAG_MIN_SAMPLES = 15
    LEV5_MODEL_DIAG_SAFETY_STEP_BPS = 0.25
    LEV5_STOP_LOSS_MTM_PCT = 0.03
    LEV5_STOP_LOSS_UPL_PCT = 0.02
    LEV5_AGGRESSIVE_MODE = True
    # 目标信号频率：从 3/小时提升至 10/小时（小步快走核心目标）
    # autotune 会自动调整参数以接近此目标；过高的目标会导致信号质量下降
    LEV5_TARGET_SIGNALS_PER_HOUR = 10
    LEV5_LOW_ACTIVITY_RELAX_Z = 0.06
    LEV5_LOW_ACTIVITY_RELAX_EDGE_BPS = 0.30
    # 强制放松阈值：40s 无信号进入一级放松，80s 进入二级（原来 28s/64s 太激进）
    # 适当延长等待时间，避免在无趋势的震荡行情中强行入场
    LEV5_FORCED_RELAX_NO_SIGNAL_SEC_1 = 40.0
    LEV5_FORCED_RELAX_NO_SIGNAL_SEC_2 = 80.0
    LEV5_FORCED_RELAX_Z_GATE = 0.72
    LEV5_MOMENTUM_FALLBACK_Z = 0.68
    LEV5_FALLBACK_CONFIRM_BAND = 0.38
    LEV5_FALLBACK_MIN_NET_EDGE_BPS_BASE = -0.15
    LEV5_FALLBACK_MIN_NET_EDGE_BPS_MAX = 0.35
    LEV5_FORCED_FAST_TRACK_MIN_EDGE_BPS = 0.10
    LEV5_FORCED_FAST_TRACK_MIN_PRED = 0.62
    # 开仓名义下限（张）；可与 LEV5_ENTRY_MIN_ORDER_CONTRACT 一起调
    LEV5_ENTRY_MIN_ORDER_CONTRACT = 0.06
    LEV5_FORCED_MIN_ORDER_CONTRACT = "0.06"
    LEV5_DYNAMIC_ACTIVITY_TARGET = True
    LEV5_ACTIVITY_VOL_REF = 0.0016
    LEV5_ACTIVITY_MIN_SIGNALS_PER_HOUR = 5
    LEV5_ACTIVITY_MAX_SIGNALS_PER_HOUR = 20
    LEV5_DIRECTIONAL_PERF_BIAS_ENABLE = True
    LEV5_DIRECTIONAL_PERF_EMA_ALPHA = 0.20
    LEV5_DIRECTIONAL_PERF_RELAX_Z = 0.02
    LEV5_DIRECTIONAL_PERF_RELAX_EDGE_BPS = 0.15
    LEV5_DIRECTIONAL_PERF_PUSH_Z = 0.01
    LEV5_DIRECTIONAL_PERF_PUSH_EDGE_BPS = 0.08
    LEV5_DIRECTIONAL_BIAS_VOL_GATE_ENABLE = True
    LEV5_DIRECTIONAL_BIAS_VOL_LOW = 0.0010
    LEV5_DIRECTIONAL_BIAS_VOL_HIGH = 0.0028
    LEV5_DIRECTIONAL_BIAS_MIN_SCALE = 0.60
    LEV5_DIRECTIONAL_BIAS_MAX_SCALE = 1.45
    LEV5_DIRECTIONAL_PERF_DIFF_BASE = 0.35
    LEV5_DIRECTIONAL_PERF_DIFF_SAMPLE_REF = 12
    LEV5_DIRECTIONAL_PERF_DIFF_MIN_SCALE = 0.70
    LEV5_DIRECTIONAL_PERF_DIFF_MAX_SCALE = 1.80
    LEV5_DIRECTIONAL_PERF_DIFF_EMA_ALPHA = 0.22
    LEV5_DIRECTIONAL_PERF_HYST_ENABLE = True
    LEV5_DIRECTIONAL_PERF_HYST_ENTER_MUL = 1.00
    LEV5_DIRECTIONAL_PERF_HYST_EXIT_MUL = 0.72
    LEV5_DIRECTIONAL_PERF_STATE_MIN_HOLD_SEC = 300.0
    LEV5_DIRECTIONAL_PERF_HOLD_DYNAMIC_ENABLE = True
    LEV5_DIRECTIONAL_PERF_HOLD_VOL_LOW = 0.0010
    LEV5_DIRECTIONAL_PERF_HOLD_VOL_HIGH = 0.0032
    LEV5_DIRECTIONAL_PERF_HOLD_MIN_SEC = 120.0
    LEV5_DIRECTIONAL_PERF_HOLD_MAX_SEC = 420.0
    LEV5_DIRECTIONAL_WINRATE_WEIGHT = 0.35
    LEV5_DIRECTIONAL_PAYOFF_WEIGHT = 0.25
    LEV5_DIRECTIONAL_SCORE_MIN_SAMPLES = 8

    # 报价时效：超过 3s 的报价视为过期，不开新仓（REST 1s 轮询下正常不触发）
    LEV5_ENTRY_MAX_QUOTE_AGE_MS = 3000.0
    # 点差上限：超过 20bps 拒绝开仓（防止在宽点差时亏损手续费）
    LEV5_ENTRY_MAX_SPREAD_BPS = 20.0
    LEV5_SOFT_FEE_TO_EQUITY_WARN = 0.010
    LEV5_VOL_LEV_SCALE_K = 35.0
    OKX_REST_MAX_ATTEMPTS = 4
    OKX_REST_RETRY_BASE_SEC = 0.38
    LEV5_POS_RECONCILE_SEC = 28.0
    LEV5_PRED_WEIGHT_FUNDING_BASIS = 0.07
    LEV5_PREDICTION_CALIBRATION_ENABLE = True
    LEV5_PREDICTION_CALIBRATION_METHOD = "platt"
    LEV5_PREDICTION_CALIBRATION_MIN_SAMPLES = 30
    LEV5_PREDICTION_CALIBRATION_ECE_INTERVAL = 25
    LEV5_PREDICTION_USE_CALIBRATED_FOR_GATE = True

    LEV5_CHOP_MERIT_MIN_MUL = 1.12
    LEV5_FEE_EQUITY_SCALE_RATIO = 0.018
    LEV5_FEE_PRESSURE_SIZE_MUL = 0.74
    LEV5_FEE_EQUITY_BLOCK_RATIO = 0.038
    LEV5_FEE_BLOCK_COOLDOWN_SEC = 480.0
    LEV5_SLIP_ADVERS_WARN_BPS = 2.15
    LEV5_SLIP_PRESSURE_Z_CAP = 0.2
    LEV5_SLIP_PRESSURE_Z_COEFF = 0.055
    LEV5_DATA_HEALTH_REST_FAIL_HARD = 8
    LEV5_DATA_HEALTH_QUOTE_AGE_STRICT_MUL = 0.82
    LEV5_VOL_LEV_SCALE_FLOOR = 0.68
    LEV5_FUNDING_BASIS_FR_SCALE = 18000.0

    # ── GridPro 专属参数（10x 网格策略）──────────────────────────────────────
    GRID_LEVELS = 4                    # 网格档数（向下放 N 档限价买单）
    GRID_ATR_WINDOW = 60               # ATR 计算窗口（tick 数，60≈12s）
    GRID_ATR_MULT = 1.2                # 格宽 = ATR × 此系数（放大以适应低ATR环境）
    # L10-001 修复 2026-04-21 21:30（静市失活问题）：
    # 市场 30min range 34bps 时，硬下限 32bps → 挂单距离 > 波动幅度 → 2h 无成交。
    # 调整为 20bps 自适应下限：
    #   - 死静市（ATR < 15bps）：spacing 被 clip 到 20bps，仍 > round-trip fee 5bps（净利 13bps）
    #   - 正常市（ATR 25-30bps）：spacing = ATR × 1.2 = 30-36bps（不触 min）
    #   - 活跃市（ATR 50bps+）：spacing = 60bps（封顶）
    # 不再硬限 min 在 32bps，市场讲事实。
    GRID_MIN_SPACING_PCT = 0.0020      # 最小格宽 20bps（允许静市贴近挂单）
    GRID_MAX_SPACING_PCT = 0.0060      # 最大格宽 60bps（极端波动时仍能成交）
    GRID_WHOLE_STOP_USDT = 5.0         # 整体止损：浮亏超此值市价平仓（50U本金的10%）
    GRID_DAILY_STOP_USDT = 6.0         # 日亏损上限：超此值当日停止（50U本金的12%，给足调试空间）
    GRID_RECENTER_MULT = 2.0           # 价格偏离 > 2×格宽 时重置中心（原1.5太激进，频繁重置浪费机会）
    GRID_ENTRY_TIMEOUT_SEC = 180.0     # 入场单 3 分钟未成交撤销（原2分钟太短）
    GRID_COOLDOWN_SEC = 120.0          # 整体止损后冷静期（原5分钟缩为2分钟，更快恢复）
    GRID_SYNC_INTERVAL_SEC = 2.0       # 查单频率（秒）
    GRID_ROUNDTRIP_FEE_BPS = 4.0       # 往返手续费（maker+maker = 2+2 bps）
    GRID_LEVERAGE = 5.0                # 网格策略杠杆（10→5，小账户爆仓保护）
    GRID_TD_MODE = "isolated"          # 逐仓模式
    GRID_WARMUP_TICKS = 30             # 热身期（原60缩为30，更快开始交易）
    GRID_DAILY_TARGET_USDT = 999.0     # 无每日上限——全天持续交易不停止（原1.5U上限是致命缺陷）
    GRID_DRAWDOWN_FROM_PEAK_USDT = 2.0 # 峰值回撤上限（适配 42U 小账户，~5%）
    # 单格张数（ETH-USDT-SWAP ctVal=0.1ETH，lotSz=1，1张=0.1ETH）。
    # 2026-04-22 适配 186U 账户：默认 1.0 张（Phase 1 基线，每格 ~$232 notional）
    GRID_CONTRACTS_PER_SLOT = 1.0
    # 单仓硬止损：Q4 盈亏比救治 2026-04-22 $1.5→$1.0（更早止损，预期 avg_loss -30%）
    GRID_PER_SLOT_STOP_USDT = 1.0
    # 【L2 做空】2026-04-20 新增
    # GRID_DIRECTION: "long" / "short" — 决定当前策略方向（一次只一个方向，不对冲）
    #  默认 "long"；Regime Router 可自动切换
    GRID_DIRECTION = "long"
    # 做空时每格张数：2026-04-22 Phase 1 基线 1.0（配合 186U 账户）
    # L10-004 教训：代码默认从 0.1 提到 1.0，即使 daemon 误删 .env 此行也不会回 0.1
    GRID_CONTRACTS_PER_SLOT_SHORT = 1.0
    # TP 距离倍率（AI R78 引入）：实际 TP = spacing × tp_mult
    GRID_TP_MULT = 1.5


# ========== 连接 / 账户（.env 必填项）==========
OKX_WS_PUBLIC_URL = _es("OKX_WS_PUBLIC_URL", "wss://ws.okx.com:8443/ws/v5/public")
_raw_ws_urls = os.environ.get("OKX_WS_PUBLIC_URLS", "").strip()
if _raw_ws_urls:
    OKX_WS_PUBLIC_URL_LIST = [x.strip() for x in _raw_ws_urls.split(",") if x.strip()]
else:
    OKX_WS_PUBLIC_URL_LIST = [OKX_WS_PUBLIC_URL, "wss://wsaws.okx.com:443/ws/v5/public"]

OKX_WS_DIRECT = _eb("OKX_WS_DIRECT", False)
OKX_WS_PROXY = os.environ.get("OKX_WS_PROXY", "").strip()
INST_ID = _es("INST_ID", "ETH-USDT-SWAP")
OKX_REST_URL = os.environ.get("OKX_REST_URL", "https://www.okx.com").rstrip("/")
_rp = os.environ.get("OKX_REST_PROXY", "").strip()
OKX_REST_HTTP_PROXY = (
    _rp
    or os.environ.get("OKX_WS_PROXY", "").strip()
    or os.environ.get("HTTPS_PROXY", "").strip()
    or os.environ.get("ALL_PROXY", "").strip()
    or os.environ.get("HTTP_PROXY", "").strip()
)
OKX_API_KEY = os.environ.get("OKX_API_KEY", "")
OKX_SECRET_KEY = os.environ.get("OKX_SECRET_KEY", "")
OKX_PASSPHRASE = os.environ.get("OKX_PASSPHRASE", "")
# ========== 运行开关（.env）==========
STRAT_LIVE = _eb("STRAT_LIVE", False)
STRAT_MODE = _es("STRAT_MODE", "grid_pro").strip().lower()
STRAT_DATA_SOURCE = _es("STRAT_DATA_SOURCE", "ws").strip().lower()

# ========== 风控（.env）==========
RISK_ENABLED = _eb("RISK_ENABLED", False)
RISK_MAX_NOTIONAL_USDT = os.environ.get("RISK_MAX_NOTIONAL_USDT", "")
RISK_MAX_ORDER_BASE = os.environ.get("RISK_MAX_ORDER_BASE", "")
RISK_MAX_CORR_NOTIONAL_USDT = os.environ.get(
    "RISK_MAX_CORR_NOTIONAL_USDT", D.RISK_MAX_CORR_NOTIONAL_USDT
)
RISK_CORR_RESYNC_INTERVAL_SEC = max(
    0.0,
    float(_ef("RISK_CORR_RESYNC_INTERVAL_SEC", float(D.RISK_CORR_RESYNC_INTERVAL_SEC))),
)
RISK_MARGIN_PRECHECK_STRICT = _eb(
    "RISK_MARGIN_PRECHECK_STRICT", D.RISK_MARGIN_PRECHECK_STRICT
)
_rdlp = os.environ.get("RISK_DAILY_MAX_LOSS_PCT", "").strip()
RISK_DAILY_MAX_LOSS_PCT = (
    float(_rdlp) if _rdlp else float(D.RISK_DAILY_MAX_LOSS_PCT)
)
# 永续：为 True 时不应用 RISK_MAX_*；单笔规模由可用 USDT×杠杆 + 执行层截断约束（见 lev5 _size_with_risk_budget）
RISK_SWAP_IGNORE_MAX_CAPS = _eb("RISK_SWAP_IGNORE_MAX_CAPS", True)
RISK_CHECK_BALANCE = D.RISK_CHECK_BALANCE
RISK_BALANCE_BUFFER_PCT = D.RISK_BALANCE_BUFFER_PCT
RISK_HALF_KELLY_ENABLE = _eb("RISK_HALF_KELLY_ENABLE", D.RISK_HALF_KELLY_ENABLE)
RISK_HALF_KELLY_WINDOW = _ei("RISK_HALF_KELLY_WINDOW", D.RISK_HALF_KELLY_WINDOW)
RISK_HALF_KELLY_MIN_SAMPLES = _ei("RISK_HALF_KELLY_MIN_SAMPLES", D.RISK_HALF_KELLY_MIN_SAMPLES)
_rhkcc = os.environ.get("RISK_HALF_KELLY_CONSERVATIVE_CONTRACTS", "").strip()
RISK_HALF_KELLY_CONSERVATIVE_CONTRACTS = (
    float(_rhkcc) if _rhkcc else float(D.RISK_HALF_KELLY_CONSERVATIVE_CONTRACTS)
)
FUNDING_BILLS_ENABLE = _eb("FUNDING_BILLS_ENABLE", D.FUNDING_BILLS_ENABLE)
_fb_int = os.environ.get("FUNDING_BILLS_FETCH_INTERVAL_SEC", "").strip()
FUNDING_BILLS_FETCH_INTERVAL_SEC = (
    float(_fb_int) if _fb_int else float(D.FUNDING_BILLS_FETCH_INTERVAL_SEC)
)

# ========== 下单规模（.env：名义区间或固定或数量）==========
_nmin = os.environ.get("STRAT_ORDER_NOTIONAL_USDT_MIN", "").strip()
_nmax = os.environ.get("STRAT_ORDER_NOTIONAL_USDT_MAX", "").strip()
_nfix = os.environ.get("STRAT_ORDER_NOTIONAL_USDT", "").strip()
STRAT_ORDER_NOTIONAL_MIN_USDT: float | None = None
STRAT_ORDER_NOTIONAL_MAX_USDT: float | None = None
STRAT_ORDER_NOTIONAL_USDT: float | None = None
if _nmin and _nmax:
    STRAT_ORDER_NOTIONAL_MIN_USDT = float(_nmin)
    STRAT_ORDER_NOTIONAL_MAX_USDT = float(_nmax)
elif _nfix:
    STRAT_ORDER_NOTIONAL_USDT = float(_nfix)

STRAT_ORDER_SZ = _es("STRAT_ORDER_SZ", D.STRAT_ORDER_SZ)
STRAT_ORDER_BASE_DECIMALS = _ei("STRAT_ORDER_BASE_DECIMALS", D.STRAT_ORDER_BASE_DECIMALS)

_strat_ot = os.environ.get("STRAT_ORDER_TYPE", "limit").strip().lower()
_STRAT_ORDER_TYPES = ("limit", "post_only", "ioc", "fok", "market")
if _strat_ot not in _STRAT_ORDER_TYPES:
    raise SystemExit(
        f"无效 STRAT_ORDER_TYPE={_strat_ot!r}，应为: {', '.join(_STRAT_ORDER_TYPES)}"
    )
STRAT_ORDER_TYPE: str = _strat_ot
STRAT_MARKET_TGT_CCY = os.environ.get("STRAT_MARKET_TGT_CCY", "").strip() or None

# ========== 库存上沿（.env 可选其一）==========
_mxb = os.environ.get("STRAT_MAX_BASE_POSITION", "").strip()
STRAT_MAX_BASE_POSITION: float | None = float(_mxb) if _mxb else None
_irf = os.environ.get("STRAT_INVENTORY_REF_BASE", "").strip()
_ima = os.environ.get("STRAT_INVENTORY_MAX_ABOVE_REF", "").strip()
STRAT_INVENTORY_REF_BASE: float | None = float(_irf) if _irf else None
STRAT_INVENTORY_MAX_ABOVE_REF: float | None = float(_ima) if _ima else None

# ========== 其余全部来自类 D 默认值（改策略请改本文件内 class D）==========
LOG_LEVEL = _es("LOG_LEVEL", "INFO")
LOG_TO_FILE = D.LOG_TO_FILE
LOG_JSONL_SNAPSHOTS = D.LOG_JSONL_SNAPSHOTS
DETAILED_DAILY_LOG = _eb("DETAILED_DAILY_LOG", D.DETAILED_DAILY_LOG)
DETAILED_LOG_PURGE_LEGACY = _eb("DETAILED_LOG_PURGE_LEGACY", D.DETAILED_LOG_PURGE_LEGACY)
DETAILED_LOG_TICK_MIN_SEC = _ef("DETAILED_LOG_TICK_MIN_SEC", D.DETAILED_LOG_TICK_MIN_SEC)

STRAT_PRICE_DECIMALS = D.STRAT_PRICE_DECIMALS

REST_POLL_INTERVAL_SEC = D.REST_POLL_INTERVAL_SEC
REST_CANDLES_BAR = D.REST_CANDLES_BAR
REST_CANDLES_LIMIT = D.REST_CANDLES_LIMIT
REST_HTTP_TIMEOUT_SEC = D.REST_HTTP_TIMEOUT_SEC
REST_HTTP_CONNECT_TIMEOUT_SEC = D.REST_HTTP_CONNECT_TIMEOUT_SEC
REST_ORDER_BOOK_SZ = D.REST_ORDER_BOOK_SZ
REST_SNAPSHOT_SLOW_INTERVAL_SEC = D.REST_SNAPSHOT_SLOW_INTERVAL_SEC

STRAT_DECISION_LOG = D.STRAT_DECISION_LOG
STRAT_DECISION_LOG_MIN_SEC = D.STRAT_DECISION_LOG_MIN_SEC
ACCOUNT_SNAPSHOT_ON_START = D.ACCOUNT_SNAPSHOT_ON_START
ACCOUNT_SNAPSHOT_INTERVAL_SEC = D.ACCOUNT_SNAPSHOT_INTERVAL_SEC

DATA_DIR = os.environ.get("DATA_DIR", str(_ROOT / "data"))
AUDIT_DB_NAME = _es("AUDIT_DB_NAME", "audit.sqlite3")
AUDIT_ENABLED = D.AUDIT_ENABLED
METRICS_INTERVAL_SEC = D.METRICS_INTERVAL_SEC
CIRCUIT_MAX_FAILS = D.CIRCUIT_MAX_FAILS
CIRCUIT_COOLDOWN_SEC = D.CIRCUIT_COOLDOWN_SEC
RECONCILE_INTERVAL_SEC = D.RECONCILE_INTERVAL_SEC

STRAT_BALANCE_POLL_SEC = D.STRAT_BALANCE_POLL_SEC
STRAT_INVENTORY_LOG_SEC = D.STRAT_INVENTORY_LOG_SEC
STRAT_STALE_ORDER_CANCEL_SEC = _ef("STRAT_STALE_ORDER_CANCEL_SEC", D.STRAT_STALE_ORDER_CANCEL_SEC)
STRAT_STALE_ORDER_POLL_SEC = D.STRAT_STALE_ORDER_POLL_SEC

LEV5_ENABLED = D.LEV5_ENABLED
LEV5_LEVERAGE = D.LEV5_LEVERAGE
LEV5_TD_MODE = D.LEV5_TD_MODE
LEV5_POS_MODE = D.LEV5_POS_MODE
LEV5_ORDER_SIZE_CONTRACT = _es("LEV5_ORDER_SIZE_CONTRACT", D.LEV5_ORDER_SIZE_CONTRACT)
LEV5_EMA_FAST_ALPHA = D.LEV5_EMA_FAST_ALPHA
LEV5_EMA_SLOW_ALPHA = D.LEV5_EMA_SLOW_ALPHA
LEV5_PULLBACK_Z = D.LEV5_PULLBACK_Z
LEV5_PULLBACK_Z_DIRECTION_TOLERANCE = D.LEV5_PULLBACK_Z_DIRECTION_TOLERANCE
LEV5_TREND_EPS = float(_es("LEV5_TREND_EPS", str(D.LEV5_TREND_EPS)))
LEV5_STOP_LOSS_PCT = float(_es("LEV5_STOP_LOSS_PCT", str(D.LEV5_STOP_LOSS_PCT)))
LEV5_TAKE_PROFIT_PCT = float(_es("LEV5_TAKE_PROFIT_PCT", str(D.LEV5_TAKE_PROFIT_PCT)))
LEV5_SL_VOL_MULT = D.LEV5_SL_VOL_MULT
LEV5_TP_VOL_MULT = D.LEV5_TP_VOL_MULT
LEV5_SL_PCT_FLOOR = D.LEV5_SL_PCT_FLOOR
LEV5_SL_PCT_CEIL = D.LEV5_SL_PCT_CEIL
LEV5_TP_PCT_FLOOR = D.LEV5_TP_PCT_FLOOR
LEV5_TP_PCT_CEIL = D.LEV5_TP_PCT_CEIL
LEV5_TP_RR_MIN = D.LEV5_TP_RR_MIN
LEV5_Z_NEED_MAX = D.LEV5_Z_NEED_MAX
LEV5_CONTINUATION_ENABLE = D.LEV5_CONTINUATION_ENABLE
LEV5_CONTINUATION_Z_MIN = D.LEV5_CONTINUATION_Z_MIN
LEV5_CONTINUATION_Z_MAX = D.LEV5_CONTINUATION_Z_MAX
LEV5_CONTINUATION_IMB_LONG = D.LEV5_CONTINUATION_IMB_LONG
LEV5_CONTINUATION_IMB_SHORT = D.LEV5_CONTINUATION_IMB_SHORT
LEV5_CONTINUATION_SIZE_FACTOR = D.LEV5_CONTINUATION_SIZE_FACTOR
LEV5_CONTINUATION_MIN_ABS_Z = D.LEV5_CONTINUATION_MIN_ABS_Z
LEV5_CONTINUATION_MIN_TREND_STRENGTH = D.LEV5_CONTINUATION_MIN_TREND_STRENGTH
LEV5_BREAKOUT_ADX_MIN = D.LEV5_BREAKOUT_ADX_MIN
_lev5_trend_ord_override = _es("LEV5_TREND_ORDER_TYPE_OVERRIDE", D.LEV5_TREND_ORDER_TYPE_OVERRIDE).strip().lower()
if _lev5_trend_ord_override not in ("limit", "post_only"):
    _lev5_trend_ord_override = "limit"
LEV5_TREND_ORDER_TYPE_OVERRIDE = _lev5_trend_ord_override
_lev5_trend_adx_raw = os.environ.get("LEV5_TREND_ORDER_TYPE_ADX_MIN", "").strip()
try:
    LEV5_TREND_ORDER_TYPE_ADX_MIN = (
        float(_lev5_trend_adx_raw) if _lev5_trend_adx_raw else float(D.LEV5_TREND_ORDER_TYPE_ADX_MIN)
    )
except (TypeError, ValueError):
    LEV5_TREND_ORDER_TYPE_ADX_MIN = float(D.LEV5_TREND_ORDER_TYPE_ADX_MIN)
LEV5_CHOP_PULLBACK_EXTRA_Z_NEED = D.LEV5_CHOP_PULLBACK_EXTRA_Z_NEED
LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS = float(
    _es("LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS", str(D.LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS))
)
LEV5_MIN_EDGE_EFFECTIVE_CEIL_BPS = float(
    _es("LEV5_MIN_EDGE_EFFECTIVE_CEIL_BPS", str(D.LEV5_MIN_EDGE_EFFECTIVE_CEIL_BPS))
)
LEV5_REST_FAIL_STREAK_WARN = D.LEV5_REST_FAIL_STREAK_WARN
LEV5_REST_FAIL_EXTRA_Z_NEED = D.LEV5_REST_FAIL_EXTRA_Z_NEED
LEV5_AUTOTUNE_Z_ADD_FLOOR = D.LEV5_AUTOTUNE_Z_ADD_FLOOR
LEV5_AUTOTUNE_Z_ADD_FLOOR_FORCED = D.LEV5_AUTOTUNE_Z_ADD_FLOOR_FORCED
LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR = D.LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR
LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR_FORCED = D.LEV5_AUTOTUNE_EDGE_ADD_HARD_FLOOR_FORCED
LEV5_STALE_HOLD_SEC = float(_es("LEV5_STALE_HOLD_SEC", str(D.LEV5_STALE_HOLD_SEC)))
LEV5_STALE_PNL_ABS_PCT = float(_es("LEV5_STALE_PNL_ABS_PCT", str(D.LEV5_STALE_PNL_ABS_PCT)))
# 快速亏损止损：达到一定持仓时间且亏损达到动态 SL 的一部分 → 提前平仓
LEV5_QUICK_LOSS_EXIT_HOLD_SEC = D.LEV5_QUICK_LOSS_EXIT_HOLD_SEC
LEV5_QUICK_LOSS_EXIT_SL_FRAC = D.LEV5_QUICK_LOSS_EXIT_SL_FRAC
LEV5_FORCE_CUT_HOLD_SEC = D.LEV5_FORCE_CUT_HOLD_SEC
LEV5_LEGACY_RELAX_ENABLE = D.LEV5_LEGACY_RELAX_ENABLE
LEV5_REGIME_CHOP_STRENGTH_MAX = D.LEV5_REGIME_CHOP_STRENGTH_MAX
LEV5_BLOCK_ENTRIES_IN_CHOP = D.LEV5_BLOCK_ENTRIES_IN_CHOP
LEV5_MIN_TREND_STRENGTH_ENTRY = D.LEV5_MIN_TREND_STRENGTH_ENTRY
LEV5_PREDICTION_GATE_ENABLE = D.LEV5_PREDICTION_GATE_ENABLE
LEV5_PREDICTION_MIN_SCORE = D.LEV5_PREDICTION_MIN_SCORE
LEV5_PREDICTION_MIN_SCORE_CHOP = D.LEV5_PREDICTION_MIN_SCORE_CHOP
LEV5_PREDICTION_CALIBRATION_ENABLE = _eb("LEV5_PREDICTION_CALIBRATION_ENABLE", D.LEV5_PREDICTION_CALIBRATION_ENABLE)
_pcal_m = _es("LEV5_PREDICTION_CALIBRATION_METHOD", D.LEV5_PREDICTION_CALIBRATION_METHOD).strip().lower()
LEV5_PREDICTION_CALIBRATION_METHOD: str = _pcal_m if _pcal_m in ("platt", "isotonic") else "platt"
LEV5_PREDICTION_CALIBRATION_MIN_SAMPLES = _ei(
    "LEV5_PREDICTION_CALIBRATION_MIN_SAMPLES", D.LEV5_PREDICTION_CALIBRATION_MIN_SAMPLES
)
LEV5_PREDICTION_CALIBRATION_ECE_INTERVAL = _ei(
    "LEV5_PREDICTION_CALIBRATION_ECE_INTERVAL", D.LEV5_PREDICTION_CALIBRATION_ECE_INTERVAL
)
LEV5_PREDICTION_USE_CALIBRATED_FOR_GATE = _eb(
    "LEV5_PREDICTION_USE_CALIBRATED_FOR_GATE", D.LEV5_PREDICTION_USE_CALIBRATED_FOR_GATE
)
LEV5_BOOK_IMB_EWM_ALPHA = D.LEV5_BOOK_IMB_EWM_ALPHA
LEV5_PRED_WEIGHT_TREND = D.LEV5_PRED_WEIGHT_TREND
LEV5_PRED_WEIGHT_PULLBACK = D.LEV5_PRED_WEIGHT_PULLBACK
LEV5_PRED_WEIGHT_IMB = D.LEV5_PRED_WEIGHT_IMB
LEV5_PRED_WEIGHT_EDGE = D.LEV5_PRED_WEIGHT_EDGE
LEV5_PRED_WEIGHT_CANDLE = D.LEV5_PRED_WEIGHT_CANDLE
LEV5_PRED_WEIGHT_SPREAD = D.LEV5_PRED_WEIGHT_SPREAD
LEV5_PRED_WEIGHT_REL_VOL = D.LEV5_PRED_WEIGHT_REL_VOL
LEV5_PRED_EDGE_SURPLUS_SCALE_BPS = D.LEV5_PRED_EDGE_SURPLUS_SCALE_BPS
LEV5_PRED_SPREAD_REF_PCT = D.LEV5_PRED_SPREAD_REF_PCT
LEV5_PRED_REL_VOL_LO = D.LEV5_PRED_REL_VOL_LO
LEV5_PRED_REL_VOL_HI = D.LEV5_PRED_REL_VOL_HI
LEV5_POST_ONLY_IMPROVE_BPS = D.LEV5_POST_ONLY_IMPROVE_BPS
LEV5_QUOTE_LOW_USDT = D.LEV5_QUOTE_LOW_USDT
LEV5_STUCK_QUOTE_LITE_SEC = D.LEV5_STUCK_QUOTE_LITE_SEC
LEV5_STUCK_QUOTE_PNL_ABS = D.LEV5_STUCK_QUOTE_PNL_ABS
LEV5_FUNDING_BLEED_HOLD_SEC = D.LEV5_FUNDING_BLEED_HOLD_SEC
LEV5_FUNDING_BLEED_FR_ABS = D.LEV5_FUNDING_BLEED_FR_ABS
LEV5_FUNDING_BLEED_MAX_PNL_FRAC_TP = D.LEV5_FUNDING_BLEED_MAX_PNL_FRAC_TP
LEV5_ACCOUNT_POS_POLL_SEC = D.LEV5_ACCOUNT_POS_POLL_SEC
LEV5_GHOST_RECONCILE_MIN_SEC = D.LEV5_GHOST_RECONCILE_MIN_SEC
LEV5_CH_AUTOTUNE_ENABLE = D.LEV5_CH_AUTOTUNE_ENABLE
LEV5_CH_AUTOTUNE_STEP = D.LEV5_CH_AUTOTUNE_STEP
LEV5_CH_W_ADJ_MIN = D.LEV5_CH_W_ADJ_MIN
LEV5_CH_W_ADJ_MAX = D.LEV5_CH_W_ADJ_MAX
LEV5_CH_PERF_EMA_ALPHA = D.LEV5_CH_PERF_EMA_ALPHA
LEV5_CH_W_PULLBACK_LONG = D.LEV5_CH_W_PULLBACK_LONG
LEV5_CH_W_CONTINUATION_LONG = D.LEV5_CH_W_CONTINUATION_LONG
LEV5_CH_W_MICRO_LONG = D.LEV5_CH_W_MICRO_LONG
LEV5_CH_W_VOL_LONG = D.LEV5_CH_W_VOL_LONG
LEV5_CH_W_FUNDING_LONG = D.LEV5_CH_W_FUNDING_LONG
LEV5_CH_W_PULLBACK_SHORT = D.LEV5_CH_W_PULLBACK_SHORT
LEV5_CH_W_CONTINUATION_SHORT = D.LEV5_CH_W_CONTINUATION_SHORT
LEV5_CH_W_MICRO_SHORT = D.LEV5_CH_W_MICRO_SHORT
LEV5_CH_W_VOL_SHORT = D.LEV5_CH_W_VOL_SHORT
LEV5_CH_W_FUNDING_SHORT = D.LEV5_CH_W_FUNDING_SHORT
LEV5_MERIT_MIN_LONG = D.LEV5_MERIT_MIN_LONG
LEV5_MERIT_MIN_SHORT = D.LEV5_MERIT_MIN_SHORT
LEV5_CH_FUNDING_STACK_FRAC = D.LEV5_CH_FUNDING_STACK_FRAC
LEV5_CH_MICRO_ENABLE = D.LEV5_CH_MICRO_ENABLE
LEV5_MICRO_IMB_LONG = D.LEV5_MICRO_IMB_LONG
LEV5_MICRO_IMB_SHORT = D.LEV5_MICRO_IMB_SHORT
LEV5_MICRO_Z_MAX_ABS = D.LEV5_MICRO_Z_MAX_ABS
LEV5_CH_VOL_BREAK_ENABLE = D.LEV5_CH_VOL_BREAK_ENABLE
LEV5_VOL_BREAK_REL_FRAC = D.LEV5_VOL_BREAK_REL_FRAC
LEV5_VOL_BREAK_Z_PAD = D.LEV5_VOL_BREAK_Z_PAD
LEV5_CH_FUNDING_ALIGN_ENABLE = D.LEV5_CH_FUNDING_ALIGN_ENABLE
LEV5_FUNDING_ALIGN_ABS = D.LEV5_FUNDING_ALIGN_ABS
LEV5_CH_SIZE_MICRO = D.LEV5_CH_SIZE_MICRO
LEV5_CH_SIZE_VOL = D.LEV5_CH_SIZE_VOL
LEV5_CH_SIZE_FUNDING = D.LEV5_CH_SIZE_FUNDING
LEV5_MAX_HOLD_SEC = D.LEV5_MAX_HOLD_SEC
LEV5_GUARD_POLL_SEC = D.LEV5_GUARD_POLL_SEC
LEV5_DAILY_DD_LIMIT_PCT = D.LEV5_DAILY_DD_LIMIT_PCT
LEV5_MAX_CONSEC_LOSS = D.LEV5_MAX_CONSEC_LOSS
LEV5_TRADING_HOURS_UTC = D.LEV5_TRADING_HOURS_UTC
LEV5_VOL_TARGET = D.LEV5_VOL_TARGET
LEV5_VOL_SOFT_CEIL = D.LEV5_VOL_SOFT_CEIL
LEV5_MIN_SIZE_FACTOR = D.LEV5_MIN_SIZE_FACTOR
LEV5_OFFHOUR_Z_BONUS = D.LEV5_OFFHOUR_Z_BONUS
LEV5_HIGHVOL_Z_BONUS = D.LEV5_HIGHVOL_Z_BONUS
LEV5_HALT_COOLDOWN_SEC = D.LEV5_HALT_COOLDOWN_SEC
LEV5_PYRAMID_ENABLE = D.LEV5_PYRAMID_ENABLE
LEV5_PYRAMID_STEP_PCT = D.LEV5_PYRAMID_STEP_PCT
LEV5_PYRAMID_MAX_LAYERS = D.LEV5_PYRAMID_MAX_LAYERS
LEV5_SCALEOUT_ENABLE = D.LEV5_SCALEOUT_ENABLE
LEV5_SCALEOUT_STEP_PCT = D.LEV5_SCALEOUT_STEP_PCT
LEV5_TRAIL_ENABLE = D.LEV5_TRAIL_ENABLE
LEV5_BREAK_EVEN_TRIGGER_PCT = D.LEV5_BREAK_EVEN_TRIGGER_PCT
LEV5_TRAIL_GIVEBACK_PCT = D.LEV5_TRAIL_GIVEBACK_PCT
LEV5_RISK_BUDGET_PCT = D.LEV5_RISK_BUDGET_PCT
LEV5_CT_VAL_BASE = D.LEV5_CT_VAL_BASE
LEV5_MIN_CONTRACTS = float(_es("LEV5_MIN_CONTRACTS", str(D.LEV5_MIN_CONTRACTS)))
LEV5_MAX_CONTRACTS = D.LEV5_MAX_CONTRACTS
LEV5_EXEC_SPREAD_FOR_POST_BPS = D.LEV5_EXEC_SPREAD_FOR_POST_BPS
LEV5_EXEC_HIGH_VOL_FOR_IOC = D.LEV5_EXEC_HIGH_VOL_FOR_IOC
LEV5_FUNDING_PENALTY_RATE = D.LEV5_FUNDING_PENALTY_RATE
LEV5_ROUNDTRIP_FEE_BPS = D.LEV5_ROUNDTRIP_FEE_BPS
LEV5_MIN_NET_EDGE_BPS = float(_es("LEV5_MIN_NET_EDGE_BPS", str(D.LEV5_MIN_NET_EDGE_BPS)))
LEV5_RUNNER_FEE_GATE_MIN_NET_EDGE_BPS = float(
    _es(
        "LEV5_RUNNER_FEE_GATE_MIN_NET_EDGE_BPS",
        str(D.LEV5_RUNNER_FEE_GATE_MIN_NET_EDGE_BPS),
    )
)
# 未显式设置 floor 时：默认 floor 不得高于 LEV5_MIN_NET_EDGE_BPS，否则仅调低 net 仍会被 0.05 锁死（gate_diag min_edge 与意图不一致）
if not os.environ.get("LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS", "").strip():
    LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS = min(
        LEV5_MIN_EDGE_EFFECTIVE_FLOOR_BPS,
        LEV5_MIN_NET_EDGE_BPS,
    )
LEV5_FUNDING_WINDOW_MIN = D.LEV5_FUNDING_WINDOW_MIN
LEV5_FUNDING_WINDOW_Z_BONUS = D.LEV5_FUNDING_WINDOW_Z_BONUS
LEV5_MICRO_POLL_SEC = D.LEV5_MICRO_POLL_SEC
LEV5_PREMIUM_ALERT_PCT = D.LEV5_PREMIUM_ALERT_PCT
LEV5_OI_DELTA_ALERT_PCT = D.LEV5_OI_DELTA_ALERT_PCT
LEV5_SELFCHECK_LOG_SEC = D.LEV5_SELFCHECK_LOG_SEC
LEV5_BOOK_IMBALANCE_ALERT = D.LEV5_BOOK_IMBALANCE_ALERT
LEV5_CONFIRM_WINDOW_SEC = D.LEV5_CONFIRM_WINDOW_SEC
LEV5_CONFIRM_Z_RELAX = D.LEV5_CONFIRM_Z_RELAX
LEV5_CONFIRM_ADAPT_ENABLE = D.LEV5_CONFIRM_ADAPT_ENABLE
LEV5_CONFIRM_FAIL_HIGH = D.LEV5_CONFIRM_FAIL_HIGH
LEV5_CONFIRM_FAIL_LOW = D.LEV5_CONFIRM_FAIL_LOW
LEV5_CONFIRM_WINDOW_MIN_SEC = D.LEV5_CONFIRM_WINDOW_MIN_SEC
LEV5_CONFIRM_WINDOW_MAX_SEC = D.LEV5_CONFIRM_WINDOW_MAX_SEC
LEV5_IMB_AGAINST_Z_BONUS = D.LEV5_IMB_AGAINST_Z_BONUS
LEV5_IMB_WITH_Z_BONUS = D.LEV5_IMB_WITH_Z_BONUS
LEV5_STALE_MICRO_SEC = D.LEV5_STALE_MICRO_SEC
LEV5_STALE_SIZE_FACTOR = D.LEV5_STALE_SIZE_FACTOR
LEV5_TUNE_INTERVAL_SEC = D.LEV5_TUNE_INTERVAL_SEC
LEV5_TUNE_Z_STEP = D.LEV5_TUNE_Z_STEP
LEV5_TUNE_EDGE_STEP_BPS = D.LEV5_TUNE_EDGE_STEP_BPS
LEV5_EDGE_MODEL_ENABLED = D.LEV5_EDGE_MODEL_ENABLED
LEV5_EDGE_Z_K_BPS = D.LEV5_EDGE_Z_K_BPS
LEV5_EDGE_IMB_K_BPS = D.LEV5_EDGE_IMB_K_BPS
LEV5_EDGE_PREMIUM_K_BPS = D.LEV5_EDGE_PREMIUM_K_BPS
LEV5_EDGE_SAFETY_BPS = D.LEV5_EDGE_SAFETY_BPS
LEV5_TUNE_MAX_STEP_SCALE = D.LEV5_TUNE_MAX_STEP_SCALE
LEV5_TUNE_FREEZE_VOL = D.LEV5_TUNE_FREEZE_VOL
LEV5_TUNE_FREEZE_PREMIUM = D.LEV5_TUNE_FREEZE_PREMIUM
LEV5_MODEL_DIAG_INTERVAL_SEC = D.LEV5_MODEL_DIAG_INTERVAL_SEC
LEV5_MODEL_DIAG_MIN_SAMPLES = D.LEV5_MODEL_DIAG_MIN_SAMPLES
LEV5_MODEL_DIAG_SAFETY_STEP_BPS = D.LEV5_MODEL_DIAG_SAFETY_STEP_BPS
LEV5_STOP_LOSS_MTM_PCT = D.LEV5_STOP_LOSS_MTM_PCT
LEV5_STOP_LOSS_UPL_PCT = D.LEV5_STOP_LOSS_UPL_PCT
LEV5_AGGRESSIVE_MODE = D.LEV5_AGGRESSIVE_MODE
LEV5_TARGET_SIGNALS_PER_HOUR = D.LEV5_TARGET_SIGNALS_PER_HOUR
LEV5_LOW_ACTIVITY_RELAX_Z = D.LEV5_LOW_ACTIVITY_RELAX_Z
LEV5_LOW_ACTIVITY_RELAX_EDGE_BPS = D.LEV5_LOW_ACTIVITY_RELAX_EDGE_BPS
LEV5_FORCED_RELAX_NO_SIGNAL_SEC_1 = D.LEV5_FORCED_RELAX_NO_SIGNAL_SEC_1
LEV5_FORCED_RELAX_NO_SIGNAL_SEC_2 = D.LEV5_FORCED_RELAX_NO_SIGNAL_SEC_2
LEV5_FORCED_RELAX_Z_GATE = D.LEV5_FORCED_RELAX_Z_GATE
LEV5_MOMENTUM_FALLBACK_Z = D.LEV5_MOMENTUM_FALLBACK_Z
LEV5_FALLBACK_CONFIRM_BAND = D.LEV5_FALLBACK_CONFIRM_BAND
LEV5_FALLBACK_MIN_NET_EDGE_BPS_BASE = float(
    _es("LEV5_FALLBACK_MIN_NET_EDGE_BPS_BASE", str(D.LEV5_FALLBACK_MIN_NET_EDGE_BPS_BASE))
)
LEV5_FALLBACK_MIN_NET_EDGE_BPS_MAX = float(
    _es("LEV5_FALLBACK_MIN_NET_EDGE_BPS_MAX", str(D.LEV5_FALLBACK_MIN_NET_EDGE_BPS_MAX))
)
LEV5_FORCED_FAST_TRACK_MIN_EDGE_BPS = float(
    _es("LEV5_FORCED_FAST_TRACK_MIN_EDGE_BPS", str(D.LEV5_FORCED_FAST_TRACK_MIN_EDGE_BPS))
)
LEV5_FORCED_FAST_TRACK_MIN_PRED = float(
    _es("LEV5_FORCED_FAST_TRACK_MIN_PRED", str(D.LEV5_FORCED_FAST_TRACK_MIN_PRED))
)
LEV5_FORCED_MIN_ORDER_CONTRACT = _es(
    "LEV5_FORCED_MIN_ORDER_CONTRACT",
    str(D.LEV5_FORCED_MIN_ORDER_CONTRACT),
)
LEV5_ENTRY_MIN_ORDER_CONTRACT = float(
    _es("LEV5_ENTRY_MIN_ORDER_CONTRACT", str(D.LEV5_ENTRY_MIN_ORDER_CONTRACT))
)
LEV5_DYNAMIC_ACTIVITY_TARGET = D.LEV5_DYNAMIC_ACTIVITY_TARGET
LEV5_ACTIVITY_VOL_REF = D.LEV5_ACTIVITY_VOL_REF
LEV5_ACTIVITY_MIN_SIGNALS_PER_HOUR = D.LEV5_ACTIVITY_MIN_SIGNALS_PER_HOUR
LEV5_ACTIVITY_MAX_SIGNALS_PER_HOUR = D.LEV5_ACTIVITY_MAX_SIGNALS_PER_HOUR
LEV5_DIRECTIONAL_PERF_BIAS_ENABLE = D.LEV5_DIRECTIONAL_PERF_BIAS_ENABLE
LEV5_DIRECTIONAL_PERF_EMA_ALPHA = D.LEV5_DIRECTIONAL_PERF_EMA_ALPHA
LEV5_DIRECTIONAL_PERF_RELAX_Z = D.LEV5_DIRECTIONAL_PERF_RELAX_Z
LEV5_DIRECTIONAL_PERF_RELAX_EDGE_BPS = D.LEV5_DIRECTIONAL_PERF_RELAX_EDGE_BPS
LEV5_DIRECTIONAL_PERF_PUSH_Z = D.LEV5_DIRECTIONAL_PERF_PUSH_Z
LEV5_DIRECTIONAL_PERF_PUSH_EDGE_BPS = D.LEV5_DIRECTIONAL_PERF_PUSH_EDGE_BPS
LEV5_DIRECTIONAL_BIAS_VOL_GATE_ENABLE = D.LEV5_DIRECTIONAL_BIAS_VOL_GATE_ENABLE
LEV5_DIRECTIONAL_BIAS_VOL_LOW = D.LEV5_DIRECTIONAL_BIAS_VOL_LOW
LEV5_DIRECTIONAL_BIAS_VOL_HIGH = D.LEV5_DIRECTIONAL_BIAS_VOL_HIGH
LEV5_DIRECTIONAL_BIAS_MIN_SCALE = D.LEV5_DIRECTIONAL_BIAS_MIN_SCALE
LEV5_DIRECTIONAL_BIAS_MAX_SCALE = D.LEV5_DIRECTIONAL_BIAS_MAX_SCALE
LEV5_DIRECTIONAL_PERF_DIFF_BASE = D.LEV5_DIRECTIONAL_PERF_DIFF_BASE
LEV5_DIRECTIONAL_PERF_DIFF_SAMPLE_REF = D.LEV5_DIRECTIONAL_PERF_DIFF_SAMPLE_REF
LEV5_DIRECTIONAL_PERF_DIFF_MIN_SCALE = D.LEV5_DIRECTIONAL_PERF_DIFF_MIN_SCALE
LEV5_DIRECTIONAL_PERF_DIFF_MAX_SCALE = D.LEV5_DIRECTIONAL_PERF_DIFF_MAX_SCALE
LEV5_DIRECTIONAL_PERF_DIFF_EMA_ALPHA = D.LEV5_DIRECTIONAL_PERF_DIFF_EMA_ALPHA
LEV5_DIRECTIONAL_PERF_HYST_ENABLE = D.LEV5_DIRECTIONAL_PERF_HYST_ENABLE
LEV5_DIRECTIONAL_PERF_HYST_ENTER_MUL = D.LEV5_DIRECTIONAL_PERF_HYST_ENTER_MUL
LEV5_DIRECTIONAL_PERF_HYST_EXIT_MUL = D.LEV5_DIRECTIONAL_PERF_HYST_EXIT_MUL
LEV5_DIRECTIONAL_PERF_STATE_MIN_HOLD_SEC = D.LEV5_DIRECTIONAL_PERF_STATE_MIN_HOLD_SEC
LEV5_DIRECTIONAL_PERF_HOLD_DYNAMIC_ENABLE = D.LEV5_DIRECTIONAL_PERF_HOLD_DYNAMIC_ENABLE
LEV5_DIRECTIONAL_PERF_HOLD_VOL_LOW = D.LEV5_DIRECTIONAL_PERF_HOLD_VOL_LOW
LEV5_DIRECTIONAL_PERF_HOLD_VOL_HIGH = D.LEV5_DIRECTIONAL_PERF_HOLD_VOL_HIGH
LEV5_DIRECTIONAL_PERF_HOLD_MIN_SEC = D.LEV5_DIRECTIONAL_PERF_HOLD_MIN_SEC
LEV5_DIRECTIONAL_PERF_HOLD_MAX_SEC = D.LEV5_DIRECTIONAL_PERF_HOLD_MAX_SEC
LEV5_DIRECTIONAL_WINRATE_WEIGHT = D.LEV5_DIRECTIONAL_WINRATE_WEIGHT
LEV5_DIRECTIONAL_PAYOFF_WEIGHT = D.LEV5_DIRECTIONAL_PAYOFF_WEIGHT
LEV5_DIRECTIONAL_SCORE_MIN_SAMPLES = D.LEV5_DIRECTIONAL_SCORE_MIN_SAMPLES

LEV5_ENTRY_MAX_QUOTE_AGE_MS = D.LEV5_ENTRY_MAX_QUOTE_AGE_MS
LEV5_ENTRY_MAX_SPREAD_BPS = D.LEV5_ENTRY_MAX_SPREAD_BPS
LEV5_SOFT_FEE_TO_EQUITY_WARN = D.LEV5_SOFT_FEE_TO_EQUITY_WARN
LEV5_VOL_LEV_SCALE_K = D.LEV5_VOL_LEV_SCALE_K
OKX_REST_MAX_ATTEMPTS = D.OKX_REST_MAX_ATTEMPTS
OKX_REST_RETRY_BASE_SEC = D.OKX_REST_RETRY_BASE_SEC
LEV5_POS_RECONCILE_SEC = D.LEV5_POS_RECONCILE_SEC
LEV5_PRED_WEIGHT_FUNDING_BASIS = D.LEV5_PRED_WEIGHT_FUNDING_BASIS

LEV5_CHOP_MERIT_MIN_MUL = D.LEV5_CHOP_MERIT_MIN_MUL
LEV5_FEE_EQUITY_SCALE_RATIO = D.LEV5_FEE_EQUITY_SCALE_RATIO
LEV5_FEE_PRESSURE_SIZE_MUL = D.LEV5_FEE_PRESSURE_SIZE_MUL
LEV5_FEE_EQUITY_BLOCK_RATIO = D.LEV5_FEE_EQUITY_BLOCK_RATIO
LEV5_FEE_BLOCK_COOLDOWN_SEC = D.LEV5_FEE_BLOCK_COOLDOWN_SEC
LEV5_SLIP_ADVERS_WARN_BPS = D.LEV5_SLIP_ADVERS_WARN_BPS
LEV5_SLIP_PRESSURE_Z_CAP = D.LEV5_SLIP_PRESSURE_Z_CAP
LEV5_SLIP_PRESSURE_Z_COEFF = D.LEV5_SLIP_PRESSURE_Z_COEFF
LEV5_DATA_HEALTH_REST_FAIL_HARD = D.LEV5_DATA_HEALTH_REST_FAIL_HARD
LEV5_DATA_HEALTH_QUOTE_AGE_STRICT_MUL = D.LEV5_DATA_HEALTH_QUOTE_AGE_STRICT_MUL
LEV5_VOL_LEV_SCALE_FLOOR = D.LEV5_VOL_LEV_SCALE_FLOOR
LEV5_FUNDING_BASIS_FR_SCALE = D.LEV5_FUNDING_BASIS_FR_SCALE

# ── GridPro 锁定参数（代码层 single source of truth，彻底忽略 .env）──────
# 2026-04-22 架构改进：主人抱怨"每次调参都要 SSH"。根因是这些参数在 .env
# 里而 .env 不进 git。解决：代码层锁定，.env 对这些 key 的设置一律忽略。
# 后果：只需 git commit + watchdog 自动部署，永远不用 SSH。
_LOCKED_GRID = {
    "GRID_CONTRACTS_PER_SLOT":       1.0,      # 主人要求 "最少得 1"
    "GRID_CONTRACTS_PER_SLOT_SHORT": 1.0,
    "GRID_LEVELS":                   3,
    # 2026-04-22 18:00 主人方案 A：回退过度止损，核心修 TP 机制
    # 深度分析发现 avg_win $0.21 只有预期 $1.31 的 16%
    # → 80% 盈利被 maybe_trail_tp + TP aging 偷走
    # → 止损本来就对，改止损是业余操作
    # → 真正该改的是：让 TP 拿全额（放严 trail + 延长 aging）
    # 2026-04-30 round65：0.8→1.0U
    # ETH 正常 ATR ≈ 30bps；0.8U=33bps 止损距离 = 1.1σ，误触发率 ~70%
    # 1.0U=42bps = 1.4σ，随机噪声触发率降至 ~50%，同时 loss_streak 连锁减少
    "GRID_PER_SLOT_STOP_USDT":       1.0,       # round65: 0.8→1.0，给正常ATR足够缓冲
    "GRID_WHOLE_STOP_USDT":          5.0,
    "GRID_DAILY_STOP_USDT":          8.0,
    "GRID_MIN_SPACING_PCT":          0.0030,
    "GRID_MAX_SPACING_PCT":          0.0080,
    "GRID_TP_MULT":                  2.0,       # 保留 2.0 —— 拉大 TP 距离
    "GRID_LEVERAGE":                 10.0,
    "GRID_DRAWDOWN_FROM_PEAK_USDT":  3.0,  # 降至6%（原12%偏高；动态覆盖=max(1.5,equity×4%)≈2U，此为备用上界）
}

def _locked(key, fallback_default):
    """锁定参数：代码优先，不读 .env。仅此字典内的 key 锁定。"""
    if key in _LOCKED_GRID:
        return _LOCKED_GRID[key]
    return fallback_default

# ── GridPro 参数导出（锁定参数代码优先；其它仍支持 .env 覆盖）────────
GRID_LEVELS        = int(_locked("GRID_LEVELS", _ei("GRID_LEVELS", D.GRID_LEVELS)))
GRID_ATR_WINDOW    = _ei("GRID_ATR_WINDOW", D.GRID_ATR_WINDOW)
GRID_ATR_MULT      = _ef("GRID_ATR_MULT", D.GRID_ATR_MULT)
GRID_MIN_SPACING_PCT   = _locked("GRID_MIN_SPACING_PCT",   _ef("GRID_MIN_SPACING_PCT",   D.GRID_MIN_SPACING_PCT))
GRID_MAX_SPACING_PCT   = _locked("GRID_MAX_SPACING_PCT",   _ef("GRID_MAX_SPACING_PCT",   D.GRID_MAX_SPACING_PCT))
GRID_WHOLE_STOP_USDT   = _locked("GRID_WHOLE_STOP_USDT",   _ef("GRID_WHOLE_STOP_USDT",   D.GRID_WHOLE_STOP_USDT))
GRID_DAILY_STOP_USDT   = _locked("GRID_DAILY_STOP_USDT",   _ef("GRID_DAILY_STOP_USDT",   D.GRID_DAILY_STOP_USDT))
GRID_RECENTER_MULT     = _ef("GRID_RECENTER_MULT",     D.GRID_RECENTER_MULT)
GRID_ENTRY_TIMEOUT_SEC = _ef("GRID_ENTRY_TIMEOUT_SEC", D.GRID_ENTRY_TIMEOUT_SEC)
GRID_COOLDOWN_SEC      = _ef("GRID_COOLDOWN_SEC",      D.GRID_COOLDOWN_SEC)
GRID_SYNC_INTERVAL_SEC = _ef("GRID_SYNC_INTERVAL_SEC", D.GRID_SYNC_INTERVAL_SEC)
GRID_ROUNDTRIP_FEE_BPS = _ef("GRID_ROUNDTRIP_FEE_BPS", D.GRID_ROUNDTRIP_FEE_BPS)
GRID_LEVERAGE          = _locked("GRID_LEVERAGE",          _ef("GRID_LEVERAGE",          D.GRID_LEVERAGE))
GRID_TD_MODE           = _es("GRID_TD_MODE",           D.GRID_TD_MODE)
GRID_WARMUP_TICKS          = _ei("GRID_WARMUP_TICKS",          D.GRID_WARMUP_TICKS)
GRID_DAILY_TARGET_USDT     = _ef("GRID_DAILY_TARGET_USDT",     D.GRID_DAILY_TARGET_USDT)
GRID_DRAWDOWN_FROM_PEAK_USDT = _locked("GRID_DRAWDOWN_FROM_PEAK_USDT", _ef("GRID_DRAWDOWN_FROM_PEAK_USDT", D.GRID_DRAWDOWN_FROM_PEAK_USDT))
GRID_CONTRACTS_PER_SLOT = _locked("GRID_CONTRACTS_PER_SLOT", _ef("GRID_CONTRACTS_PER_SLOT", D.GRID_CONTRACTS_PER_SLOT))
GRID_PER_SLOT_STOP_USDT = _locked("GRID_PER_SLOT_STOP_USDT", _ef("GRID_PER_SLOT_STOP_USDT", D.GRID_PER_SLOT_STOP_USDT))
GRID_DIRECTION = _es("GRID_DIRECTION", D.GRID_DIRECTION).strip().lower()
GRID_CONTRACTS_PER_SLOT_SHORT = _locked("GRID_CONTRACTS_PER_SLOT_SHORT", _ef("GRID_CONTRACTS_PER_SLOT_SHORT", D.GRID_CONTRACTS_PER_SLOT_SHORT))
GRID_TP_MULT = _locked("GRID_TP_MULT", _ef("GRID_TP_MULT", D.GRID_TP_MULT))
DATA_DIR               = _es("DATA_DIR",               "./data")


def compute_inventory_cap(
    legacy_max: float | None,
    ref: float | None,
    above: float | None,
) -> tuple[float | None, dict[str, Any]]:
    """解析有效 base 上沿与元数据（供日志与快照）。"""
    meta: dict[str, Any] = {
        "mode": "none",
        "ref": ref,
        "above": above,
        "legacy_max": legacy_max,
        "effective_max": None,
    }
    if ref is not None and ref > 0 and above is not None and above >= 0:
        m = ref + above
        meta["mode"] = "range"
        meta["effective_max"] = m
        return m, meta
    if ref is not None and ref > 0:
        meta["mode"] = "ref_cap"
        meta["effective_max"] = ref
        return ref, meta
    if legacy_max is not None and legacy_max > 0:
        meta["mode"] = "legacy"
        meta["effective_max"] = legacy_max
        return legacy_max, meta
    return None, meta


STRAT_INVENTORY_EFFECTIVE_MAX_BASE, STRAT_INVENTORY_META = compute_inventory_cap(
    STRAT_MAX_BASE_POSITION,
    STRAT_INVENTORY_REF_BASE,
    STRAT_INVENTORY_MAX_ABOVE_REF,
)


def new_run_id() -> str:
    """一次 runner 进程会话 ID（原 quant.core.runtime）。"""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    return f"{ts}-{uuid.uuid4().hex[:8]}"


__all__ = [n for n in globals() if n.isupper() and not n.startswith("_")]
if "compute_inventory_cap" not in __all__:
    __all__.append("compute_inventory_cap")
if "new_run_id" not in __all__:
    __all__.append("new_run_id")
